default_agent: multiserver_mcp_agent
agents:
  langgraph_math_streaming:
    name: langgraph_math_streaming
    entrypoint: /workspaces/agent_core_deep_research/langgraph_streaming/agentcore_langgraph_math_streaming.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::482387069690:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-0dc38f05bb
      execution_role_auto_create: false
      account: '482387069690'
      region: us-west-2
      ecr_repository: 482387069690.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-langgraph_math_streaming
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: langgraph_math_streaming-D1rmXq5o62
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:482387069690:runtime/langgraph_math_streaming-D1rmXq5o62
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-langgraph_math_streaming-builder
      execution_role: arn:aws:iam::482387069690:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-0dc38f05bb
      source_bucket: bedrock-agentcore-codebuild-sources-482387069690-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
  multiserver_mcp_agent:
    name: multiserver_mcp_agent
    entrypoint: /workspaces/agent_core_deep_research/MultiServerMCPClient/agentcore_remote_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::482387069690:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-e9a27090f2
      execution_role_auto_create: false
      account: '482387069690'
      region: us-west-2
      ecr_repository: 482387069690.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-multiserver_mcp_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: multiserver_mcp_agent-QlSXuKFOnc
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:482387069690:runtime/multiserver_mcp_agent-QlSXuKFOnc
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-multiserver_mcp_agent-builder
      execution_role: arn:aws:iam::482387069690:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-e9a27090f2
      source_bucket: bedrock-agentcore-codebuild-sources-482387069690-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
